/* == MSENGINE.HPP ========================================================= **
** ######################################################################### **
** ## MS-ENGINE              Copyright (c) MS-Design, All Rights Reserved ## **
** ######################################################################### **
** ## This file is automatically generated by build. Changes are lost     ## **
** ## when the engine is rebuilt.                                         ## **
** ######################################################################### **
** ========================================================================= */
#pragma once                           // Only one incursion allowed
/* ------------------------------------------------------------------------- */
#define VER_NAME    "MS-Engine"                       // Name of engine
#define VER_AUTHOR  "MS-Design"                       // Author of engine
#define VER_MAJOR   24                                // Version major (year)
#define VER_MINOR   6                                 // Version minor (month)
#define VER_BUILD   14                                // Version build (day)
#define VER_REV     8                                 // Version rev (build#)
#define VER_STR_NQ  24,6,14,8                         // Version as literal
#define VER_STR     "24.6.14.8"                       // Version as string
#define VER_DATE    "Fri Jun 14 16:49:09 2024 +0100"  // Compilation date
/* == EoF =========================================================== EoF == */
