/* == MSENGINE.HPP ========================================================= **
** ######################################################################### **
** ## MS-ENGINE              Copyright (c) MS-Design, All Rights Reserved ## **
** ######################################################################### **
** ## This file is automatically generated by build. Changes are lost     ## **
** ## when the engine is rebuilt.                                         ## **
** ######################################################################### **
** ========================================================================= */
#pragma once                           // Only one incursion allowed
/* ------------------------------------------------------------------------- */
#define VER_NAME    "MS-Engine"                       // Name of engine
#define VER_AUTHOR  "MS-Design"                       // Author of engine
#define VER_MAJOR   24                                // Version major (year)
#define VER_MINOR   4                                 // Version minor (month)
#define VER_BUILD   1                                 // Version build (day)
#define VER_REV     91                                // Version rev (build#)
#define VER_STR_NQ  24,4,1,91                         // Version as literal
#define VER_STR     "24.4.1.91"                       // Version as string
#define VER_DATE    "Mon Apr 01 15:05:10 2024 +0100"  // Compilation date
/* == EoF =========================================================== EoF == */
